### ISSUE TITLE
Helper version

### ISSUE THREAD

**Issue by mschinis** [zestia/ember-wrap-urls#1]
Hello,

It would be very interesting to see this addon in a helper format, so that you could use something like the following:

`(some-other-helper (wrap-urls "hey check this cool product http://somethingcool.com"))`

**Comment by amk221** [comment]
Interestingly, my first attempt at _this was a [helper](https://gist.github.com/amk221/d3fb5eb6e3ef091baea02cd8824123fd)_.

However, there were a couple of issues...

1. `wrap-urls` is a dead-end. Therefore, being able to call it as a helper isn't useful. Consider:

**ok**
```
{{wrap-urls text=(truncate 'visit http://example.com' 19)}}
```
Which results in: `visit <span class="ember-view url">http://exampl</span>`

**not ok**
```
{{truncate (wrap-urls 'visit http://example.com') 19}}
```
Which _could_ result in: `visit <span class="`
(However, it won't because `span` is not an HTML string)

2. The result of calling `wrap-urls` needs to contain components (not just plain HTML strings). I didn't know how to do this.... Helpers don't have HTMLBars templates, so I opted for a Component.
It's probably possible to achieve using streams, but I am unfamiliar with them.

I'd appreciate any help on the matter

**Comment by mschinis** [comment]
1. Truncating example
If you were to use the hyperlink component, I imagine that even the first *ok* example wouldn't work either. It will link to `http://exampl`, right?.

2. Containing components
I think you can return components from a helper by doing the following:

```javascript
import hbs from 'htmlbars-inline-precompile';
export function someHelper([component]) {
    return hbs`{{${component}}}{{/${component}}}`;
}
export default Ember.Helper.helper(someHelper);
```

I haven't tried the above yet, but that should work.

I'll have a crack at it, later in the weekend and let you know how it goes :)

**Comment by amk221** [comment]
@mschinis 
1. Example 1 does work, as there is a [test](https://github.com/amk221/ember-wrap-urls/blob/master/tests/integration/components/wrap-urls-test.js#L66)

2. I don't think many people include the template compiler in production so that would be no use
